export const extraProducts = [
  {
    id: 21,
    title: "Men's Slim Fit Cotton Shirt",
    price: 25.99,
    description: "Comfortable and stylish cotton shirt for casual wear.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UX679_.jpg",
    rating: { rate: 4.2, count: 130 },
  },
  {
    id: 22,
    title: "Women's Casual Maxi Dress",
    price: 34.99,
    description: "Elegant maxi dress with floral design and breathable fabric.",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    rating: { rate: 4.6, count: 90 },
  },
  {
    id: 23,
    title: "Wireless Bluetooth Earbuds",
    price: 59.99,
    description:
      "Noise-cancelling earbuds with high-quality sound and long battery life.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    rating: { rate: 4.4, count: 250 },
  },
  {
    id: 24,
    title: "Gold Plated Heart Necklace",
    price: 18.49,
    description: "Delicate gold-plated necklace with heart pendant.",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71yaIMZ+xnL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.1, count: 70 },
  },
  {
    id: 25,
    title: "Men's Classic Leather Wallet",
    price: 21.89,
    description:
      "Genuine leather wallet with RFID protection and multiple compartments.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    rating: { rate: 4.7, count: 140 },
  },
  {
    id: 26,
    title: "Women's Handbag with Shoulder Strap",
    price: 49.99,
    description:
      "Elegant handbag with detachable shoulder strap and spacious interior.",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.3, count: 100 },
  },
  {
    id: 27,
    title: "Smart Fitness Tracker",
    price: 39.99,
    description: "Tracks steps, heart rate, and sleep with smartphone sync.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    rating: { rate: 4.5, count: 210 },
  },
  {
    id: 28,
    title: "Sterling Silver Drop Earrings",
    price: 22.75,
    description: "Elegant sterling silver earrings with teardrop design.",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.0, count: 50 },
  },
  {
    id: 29,
    title: "Men's Casual Canvas Sneakers",
    price: 29.95,
    description: "Lightweight canvas sneakers for everyday use.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_UX679_.jpg",
    rating: { rate: 4.6, count: 85 },
  },
  {
    id: 30,
    title: "Women's Wool Knit Sweater",
    price: 45.0,
    description: "Warm and cozy sweater perfect for winter.",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    rating: { rate: 4.4, count: 110 },
  },
  {
    id: 31,
    title: "Wireless Charging Pad",
    price: 19.99,
    description: "Fast wireless charging pad compatible with all Qi devices.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    rating: { rate: 4.3, count: 175 },
  },
  {
    id: 32,
    title: "18K Gold Chain Bracelet",
    price: 58.99,
    description: "Elegant and simple 18K gold chain bracelet.",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71Yg9D3lZaL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.7, count: 95 },
  },
  {
    id: 33,
    title: "Men's Pack of 3 T-Shirts",
    price: 28.99,
    description: "Soft cotton crew neck t-shirts in black, white, and gray.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/61bK6PMOC3L._AC_UX679_.jpg",
    rating: { rate: 4.1, count: 60 },
  },
  {
    id: 34,
    title: "Women's Skinny Jeans",
    price: 37.99,
    description: "Stretchable skinny jeans with modern cut and high waist.",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    rating: { rate: 4.5, count: 75 },
  },
  {
    id: 35,
    title: "Portable Bluetooth Speaker",
    price: 44.5,
    description: "Waterproof and portable speaker with deep bass.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/61Wux4U3gKL._AC_SX679_.jpg",
    rating: { rate: 4.6, count: 160 },
  },
  {
    id: 36,
    title: "Rose Gold Stud Earrings",
    price: 16.75,
    description: "Elegant rose gold plated stud earrings for daily wear.",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71yaIMZ+xnL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.0, count: 40 },
  },
  {
    id: 37,
    title: "Men's Zip Up Hoodie",
    price: 49.99,
    description: "Fleece-lined hoodie for comfort and warmth.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    rating: { rate: 4.3, count: 90 },
  },
  {
    id: 38,
    title: "Women's Bomber Jacket",
    price: 64.99,
    description: "Stylish bomber jacket with zip closure and ribbed cuffs.",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    rating: { rate: 4.4, count: 100 },
  },
  {
    id: 39,
    title: "Smart Home Plug",
    price: 15.99,
    description:
      "Voice-controlled smart plug compatible with Alexa and Google.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    rating: { rate: 4.2, count: 130 },
  },
  {
    id: 40,
    title: "Silver Infinity Necklace",
    price: 26.49,
    description: "Simple and meaningful infinity symbol necklace in silver.",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.5, count: 55 },
  },
  {
    id: 41,
    title: "Men's Fleece Joggers",
    price: 32.0,
    description: "Cozy fleece joggers perfect for workouts or lounging.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/61bK6PMOC3L._AC_UX679_.jpg",
    rating: { rate: 4.6, count: 70 },
  },
  {
    id: 42,
    title: "Women's Leather Boots",
    price: 89.99,
    description: "Durable and fashionable boots with a modern edge.",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    rating: { rate: 4.7, count: 85 },
  },
  {
    id: 43,
    title: "Noise-Isolating Headphones",
    price: 69.99,
    description: "Over-ear headphones with powerful sound and soft padding.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    rating: { rate: 4.5, count: 200 },
  },
  {
    id: 44,
    title: "Gold-Plated Hoop Earrings",
    price: 20.99,
    description: "Shiny and bold hoop earrings for statement looks.",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71Yg9D3lZaL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.1, count: 45 },
  },
  {
    id: 45,
    title: "Men's Stretch Dress Pants",
    price: 54.0,
    description: "Slim fit dress pants with wrinkle-resistant fabric.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UX679_.jpg",
    rating: { rate: 4.4, count: 95 },
  },
  {
    id: 46,
    title: "Women's Lace Blouse",
    price: 42.5,
    description: "Delicate lace blouse with intricate details.",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    rating: { rate: 4.2, count: 60 },
  },
  {
    id: 47,
    title: "USB-C Wall Charger",
    price: 12.99,
    description: "Compact charger with fast charging USB-C port.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/61Wux4U3gKL._AC_SX679_.jpg",
    rating: { rate: 4.6, count: 185 },
  },
  {
    id: 48,
    title: "Crystal Pendant Necklace",
    price: 29.75,
    description: "Sparkling crystal pendant on delicate chain.",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71yaIMZ+xnL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.3, count: 52 },
  },
  {
    id: 49,
    title: "Men's Flannel Shirt",
    price: 38.25,
    description: "Soft and warm flannel for fall and winter.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    rating: { rate: 4.5, count: 78 },
  },
  {
    id: 50,
    title: "Women's High-Waist Yoga Pants",
    price: 30.99,
    description: "Breathable yoga pants with tummy control design.",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    rating: { rate: 4.8, count: 98 },
  },
];
